# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import res
from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Gradient Descender")
        Form.resize(500, 600)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 30, 460, 550))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 400, 490))
        self.label.setStyleSheet("border-image: url(:/images/blanc.jpeg);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 400, 490))
        self.label_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.42, radius:0.88, fx:0.5, fy:0.75, stop:0 rgba(0, 0, 0, 40), stop:1 rgba(0, 0, 0, 50));\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 300, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(100, 110, 130, 50);\n"
"color:rgba(255, 255, 255, 200);\n"
"padding-bottom:3px")
        self.lineEdit.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 360, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(100, 110, 130, 50);\n"
"color:rgba(255, 255, 255, 200);\n"
"padding-bottom:3px")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(160, 440, 131, 51))
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.42, radius:0.88, fx:0.5, fy:0.75, stop:0 rgba(0, 0, 0, 40), stop:1 rgba(0, 0, 0, 150));\n"
"    color:rgba(255, 255, 255, 150);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.42, radius:0.88, fx:0.5, fy:0.75, stop:0 rgba(0, 0, 0, 40), stop:1 rgba(150, 150, 150, 150));\n"
"    color:rgba(255, 255, 255, 150);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.42, radius:0.88, fx:0.5, fy:0.75, stop:0 rgba(0, 0, 0, 40), stop:1 rgba(180, 180, 180, 150));\n"
"    color:rgba(0, 0, 0, 150);\n"
"    border-radius:20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=30, xOffset=0, yOffset=0, color=QtGui.QColor(230, 220, 185, 100)))
        self.pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=2, yOffset=2, color=QtGui.QColor(100, 110, 130, 100)))
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "username"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "password"))
        self.pushButton.setText(_translate("Form", "LOGIN"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        login_screen = QtWidgets.QWidget()
        gui = Ui_Form()
        gui.setupUi(login_screen)
        login_screen.show()
        sys.exit(app.exec())